[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Grzegorz Nowak"]
description = "A starter project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/spottmedia/rust-wasm-starter"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"